# Generated by Django 3.2 on 2026-01-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_playerscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscore',
            old_name='player_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='playerscore',
            old_name='player_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='playerscore',
            old_name='player_name',
            new_name='name',
        ),
    ]
