# Generated by Django 3.2 on 2026-01-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20260114_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
